name: Show Secrets and Variables

on:
  workflow_dispatch:

jobs:
  print_values:
    runs-on: ubuntu-latest

    steps:
      - name: Print Variable and Secret
        env:
          MY_VARIABLE: ${{ vars.MY_VARIABLE }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
          
        run: |
          echo "Variable: $MY_VARIABLE"
          echo "Secret: $MY_SECRET"
          echo $MY_SECRET >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
        # chmod 600 secrets.txt # Ensure only the owner can read/write
        # Copy ssh link from github action the run it localy 
        # To view secrets: cat secrets.txt
        # To end run: touch continue

