name: Show Secrets and Variables

on:
  workflow_dispatch:

jobs:
  print_values:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run: |
          echo "Variable: ${{ vars.MY_VARIABLE }}"

      - name: Print secret
        run: |
          echo "Secret: ${{ secrets.MY_SECRET }}"

      - name: Run tmate (To make secrets visible)
        uses: mxschmitt/action-tmate@v2
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo $MY_SECRET >> secrets.txt
        # Copy ssh link from github action the run it localy 
        # To view secrets: cat secrets.txt
        # To end run: touch continue